
# Project information
site_name: 'Nefry'
site_description: 'フリスクサイズのIoTデバイス'
site_author: 'Nefry-community'
site_dir: 'site/'
site_url: 'https://nefry.studio/'

extra_css: ['extra.css']

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/Nefry-Community/Arduino'

# Copyright
copyright: 'Copyright (c) 2016-2018 Nefry Community'

# Documentation and theme
docs_dir: 'docs'
theme:
  name: 'material'
  language: 'ja'
  logo: 'cloud'
  palette:
    primary: 'Orange'
    accent: 'Purple'
# Options
extra:
  search:
    language: 'jp'
  version: '2.3.0'
  author:
    github: 'wamisnet'
    twitter: 'wamisnet'

# Google Analytics
google_analytics:
  - 'UA-62256925-4'
  - 'auto'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc
