version: 2
jobs:
  build:
    docker:
      - image: squidfunk/mkdocs-material:2.7.3
    steps:
      - checkout
      - run:
          name: git config setting
          command: |
            git config --global user.email "wamiwami@live.jp"
            git config --global user.name "wami"
      - run:
          name: Build Web
          command: mkdocs gh-deploy -m "Update [ci skip]"
