version: 2
jobs:
  build:
    docker:
      - image: squidfunk/mkdocs-material:2.7.3
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
             - "a8:ec:fb:03:9f:cc:10:38:14:10:a4:04:48:72:2d:ea"
      - run:
          name: Build Web
          command: mkdocs gh-deploy -m "Update [ci skip]"
